#!/bin/bash -ex
install()
{
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}

install sudo cmake bison build-essential boost-build mercurial screen apache2 mysql-server phpmyadmin rrdtool \
  libgl1-mesa-dev libopenal-dev libogg-dev libvorbis-dev libluabind-dev libfreetype6-dev \
  libpng12-dev libjpeg62-dev libx11-dev libxxf86vm-dev libxrandr-dev libxrender-dev \
  libcurl4-openssl-dev libxmu-dev libexpat1-dev libxml2-dev libmysqlclient-dev zlib1g-dev

adduser ryzom --disabled-password --gecos ''

cat >/etc/sudoers.d/ryzom <<EOF
ryzom  ALL=(ALL) NOPASSWD: ALL
EOF
chmod 0440 /etc/sudoers.d/ryzom

su ryzom -c /usr/local/bin/ryzom_install

HOSTNAME=ryzom
echo "$HOSTNAME" > /etc/hostname
sed -i "s|127.0.1.1 \(.*\)|127.0.1.1 $HOSTNAME|" /etc/hosts

rm -r /var/cache/apt/*
mkdir /var/cache/apt/archives
mkdir /var/cache/apt/archives/partial
